/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpeedNumber;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author hai
 */
public class BLNDocumentListener_app extends javax.swing.JFrame {
String str3 = "tanhai15101992";
    /**
     * Creates new form BLNDocumentListener_app
     */
    public BLNDocumentListener_app() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgResult = new javax.swing.JDialog();
        lbCorrect = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        tf = new javax.swing.JTextField();

        dlgResult.setSize(new java.awt.Dimension(300, 200));

        lbCorrect.setText("Correct :");

        btn.setText("Continue");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgResultLayout = new javax.swing.GroupLayout(dlgResult.getContentPane());
        dlgResult.getContentPane().setLayout(dlgResultLayout);
        dlgResultLayout.setHorizontalGroup(
            dlgResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgResultLayout.createSequentialGroup()
                .addGroup(dlgResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgResultLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgResultLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btn)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        dlgResultLayout.setVerticalGroup(
            dlgResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgResultLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 200));

        tf.getDocument().addDocumentListener(new MyDocumentListener());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
      dlgResult.setVisible(false);
      tf.setText("");
      tf.setEditable(true);
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BLNDocumentListener_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BLNDocumentListener_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BLNDocumentListener_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BLNDocumentListener_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLNDocumentListener_app().setVisible(true);
            }
        });
    }
class MyDocumentListener implements DocumentListener{

        @Override
        public void insertUpdate(DocumentEvent de) {
            change();
        }

        @Override
        public void removeUpdate(DocumentEvent de) {
          
        }

        @Override
        public void changedUpdate(DocumentEvent de) {
       
        }
    public void change(){
        int index = tf.getText().length();
        String str1 = str3.charAt(index-1)+"";
        String str2 = tf.getText().substring(index-1)+"";
        
        if(str1.equals(str2)){
            if(index == 14){
                tf.setEditable(false);
                dlgResult.setVisible(true);
                lbCorrect.setText("Correct:    "+index+"/14");
            }
        }
        else{
            tf.setEditable(false);
            dlgResult.setVisible(true);
            lbCorrect.setText("Correct:    "+(index-1)+"/14");
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JDialog dlgResult;
    private javax.swing.JLabel lbCorrect;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
